- repo: git@github.com:coyainsurance/pre-commit-scalafmt.git
  sha: master # you probably do not want to use latest version, but rather pin it to specific commit and update manually
  hooks:
    - id: scalafmt
      args: [ -p9090, -t ] # run in server mode on port 9090 and pass `--test` to scalafmt; alternatively you can place here other supported cmdline arguments
